#!/bin/bash

set -ex

wget --no-check-certificate  https://figshare.com/ndownloader/files/39149009/SCE_DLPFC-n3_tran-etal.rda

#invoke build --env-name=root --no-kernel
#invoke demofiles
#invoke talk -t demo
#rm -rf demofiles
#rm -rf notebooks
#rm -rf narrative
#rm -rf slides
#rm demo/notebooks/Julia.ipynb
#jupyter lab clean

# Setup a workspace
#jupyter lab workspaces import binder/workspace.json
